### PR TITLE
Bot announce changes

### PR DESCRIPTION
**Pull request by SimplyJpk**
Can now organize announcements that'll show the next time the bot restarts, or right away.

It also posts a simple "Server started." message when it starts into the normal bot-announcements channel. This isn't visible to normal users, easy enough to change if desired.

**new commands**

**!announce help** (Shows information about commands)

**!announce new message_id send_now\***
(Will copy the contents including formatting of ``message_id`` and add to a list that is saved, the next time the bot starts, it will post these into the channel that the new setting ``Settings.UpdateNewsChannel`` points to. if send_now is true it'll just copy the content and post them into UpdateNewsChannel)

**!announce clear** (clears the stored announcement list and saves)

**!announce preview** (Will post the entire announcement list into the channel this command is used in)

Did some testing, didn't find any problems. 

This PR does contain some QOL features from branch I'm working on locally however.
- deserializer which should simplify settings saving/loading (also for first time startup)
- Simple console log which should make problems more obvious (hopefully)
- A database test, checks the command string works, and tests to make sure the table `users` exists. 

Should be feature complete enough for #12

### CODE REVIEW

**Comment by Pierre-Demessence** [comment]
Can you give some use case for this feature ? Because I don't really understand what it does and why. 🤔 

For #12 I was really thinking something terribly simple, like:
OnBotReady => Send "Bot Started" (harcoded) in `#bot-commands` (using the already defined ID).

**Comment by SimplyJpk** [comment]
Think I misread the issue, I might just make this into a couple Pull Requests

Most of what this does is act as an announcement service, you can format a message in a private channel and then tell the bot to copy the message and post it into a specified channel which it'll do either right away, or the next time the bot starts (Presumably after an upgrade/new features have been merged).

It also just says when the bot starts into the ``#bot-announcement`` channel, that can easily change that to ``#bot-commands``

**Comment by Pierre-Demessence** [comment]
I meant #bot-announcement, not #bot-commands mb, so that's good!

**Comment by SimplyJpk** [comment]
Closing this since useless 🦘

**Pull request closed without merging**
