### PR TITLE
Start of Weather Command

### PR DESCRIPTION
**Pull request by SimplyJpk**
InternetExtensions has a GetHttpContents which returns string of a page. This can be used for other modules/commands

UserModule has
!temp city
- Returns temp of city (Celcius)
!weather city
- Very simple weather result, temp, Description + Humidty

This still needs a fair bit of work, I did most of this earlier in the year and then got bored. I may revisit this if someone doesn't beat me to it down the line.

API Used: https://openweathermap.org/current#call
API Results: JSON -> https://openweathermap.org/current#current_JSON

Things that need doing
- [x] API in settings 
- [ ] Generating new key
- [x] Format !temp to be more than just number in celcius
- [x] Format !weather better

Other Ideas
- [ ] Compare Method? ie; !tempcomp Canberra London

### CODE REVIEW

**Comment by Pierre-Demessence** [comment]
If this API is more accurate when querying locations (with the `?q` parameter), we could switch to it for the `!time` command as it gives a `timezone` parameter which can be used to calculate local time.
image

**Comment by Pierre-Demessence** [comment]
For this PR itself:

- Showing both °C and °F is better than providing 2 commands.
- The API Key to be used in Production should be put in 1password.

**Comment by SimplyJpk** [comment]
image

More commands can be added later, but what is here is functional. we just need to move key to settings and add to 1pass.

I did look at converting the !time to use the same API, but it doesn't provide as much detail, daylight savings isn't in the data sadly. Country and City Name are included, and it does try to match them a lot harsher so the "random" results we get from !time wouldn't be a problem here. But if we want to include DTS we'd need to work out another method for getting that. (If we ended up converting !time to use same API)

**Comment by Pierre-Demessence** [comment]
Do we need 2 different commands ?
It feels like the only difference is that ?temp has the humidity. Other than that, there's actually **more info** about temperature on the ?weather command (since there's the min and max).

So we could just add the humidity to the first command, and make ?temp and ?weather aliases. What do you think @SimplyJpk ?

**Comment by Pierre-Demessence** [comment]
As for the `?time` command using this API, we can scrap the DST, it's not that important.
This cons is far outweighed from the pro of:
- Having a more precise API
- Using only 1 API instead of 2

**Comment by SimplyJpk** [comment]
I looked into using weather api for ``!time``, it is pretty doable, however.. it won't do locations like "NSW" or "UK" since it only accepts cities, or lon/lat which is even less helpful.

I imagine most people would try use this API for locations and less about cities. We could use both, and if weather fails to return a result use ``!time`` however then we still end up with the results for bogus inputs.

**Comment by SimplyJpk** [comment]
image
Unless we have more ideas for this module, I'm ready to call it done.

I don't have access to add passwords to onepass (last I checked) so you'll have to add the new key.

**Pull request merged**
